import { test, expect, sel } from '../../helpers/app.mjs'

const CACHED_CHANNEL_ID = 'UCaaaaaaaaaaaaaaaaaaaaaa'
const UNKNOWN_CHANNEL_ID = 'UCbbbbbbbbbbbbbbbbbbbbbb'
const ONE_THUMBNAIL_CHANNEL_ID = 'UCcccccccccccccccccccccc'
const EMPTY_THUMBNAIL_CHANNEL_ID = 'UCdddddddddddddddddddddd'
const AVATAR_PNG = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg=='

test.use({
  seed: {
    settings: {
      backendPreference: 'invidious',
      backendFallback: false,
      defaultInvidiousInstance: 'https://invidious.test'
    },
    profiles: [{
      _id: 'allChannels',
      name: 'All Channels',
      bgColor: '#000000',
      textColor: '#FFFFFF',
      subscriptions: [{
        id: CACHED_CHANNEL_ID,
        name: 'Deleted Channel',
        thumbnail: 'data:image/png;base64,invalid'
      }, {
        id: EMPTY_THUMBNAIL_CHANNEL_ID,
        name: 'Saved Thumbnail Channel',
        thumbnail: 'https://yt3.googleusercontent.com/saved-avatar=s176'
      }]
    }]
  }
})

async function openChannelTab(page, channelId) {
  const tab = await page.evaluate((id) => window.ftElectron.tabs.create({
    route: `/channel/${id}`,
    makeActive: false
  }), channelId)
  await page.locator(`.tab[data-tab-id="${tab.id}"]`).click()
}

function invidiousChannelResponse(author, authorId, authorThumbnails) {
  return {
    author,
    authorId,
    authorUrl: '',
    authorVerified: false,
    authorBanners: [],
    authorThumbnails,
    subCount: 0,
    totalViews: 0,
    joined: 0,
    autoGenerated: false,
    isFamilyFriendly: true,
    description: '',
    descriptionHtml: '',
    allowedRegions: [],
    tabs: [],
    latestVideos: [],
    relatedChannels: []
  }
}

test('renders a channel with one Invidious thumbnail', async ({ page }) => {
  await page.route(`https://invidious.test/api/v1/channels/${ONE_THUMBNAIL_CHANNEL_ID}?*`, route => route.fulfill({
    json: invidiousChannelResponse('One Thumbnail', ONE_THUMBNAIL_CHANNEL_ID, [{
      url: '//yt3.ggpht.com/e2e-avatar.png',
      width: 88,
      height: 88
    }])
  }))
  await page.route('https://invidious.test/ggpht/e2e-avatar.png', route => route.fulfill({
    body: Buffer.from(AVATAR_PNG, 'base64'),
    contentType: 'image/png'
  }))

  await openChannelTab(page, ONE_THUMBNAIL_CHANNEL_ID)

  const channel = page.locator('.channelDetails:visible')
  await expect(channel.locator('.name')).toHaveText('One Thumbnail')
  await expect(channel.locator('.info')).not.toHaveClass(/infoHasError/)
  await expect(channel.locator('img.thumbnail')).toHaveAttribute(
    'src',
    'https://invidious.test/ggpht/e2e-avatar.png'
  )
})

test('renders a channel fallback for an empty Invidious thumbnail array', async ({ page }) => {
  await page.route(`https://invidious.test/api/v1/channels/${EMPTY_THUMBNAIL_CHANNEL_ID}?*`, route => route.fulfill({
    json: invidiousChannelResponse('No Thumbnail', EMPTY_THUMBNAIL_CHANNEL_ID, [])
  }))

  await openChannelTab(page, EMPTY_THUMBNAIL_CHANNEL_ID)

  const channel = page.locator('.channelDetails:visible')
  await expect(channel.locator('.name')).toHaveText('No Thumbnail')
  await expect(channel.locator('.info')).not.toHaveClass(/infoHasError/)
  await expect(channel.locator('img.thumbnail')).toHaveCount(0)
  await expect(channel.locator('.thumbnail:not(img)')).toBeVisible()
  await expect.poll(() => page.evaluate((channelId) => {
    const store = document.querySelector('#app').__vue_app__.config.globalProperties.$store
    return store.getters.getActiveProfile.subscriptions.find(subscription => subscription.id === channelId)?.thumbnail
  }, EMPTY_THUMBNAIL_CHANNEL_ID)).toBe('https://yt3.googleusercontent.com/saved-avatar=s176')
})

test('shows fallback metadata for unavailable channels', async ({ page }) => {
  await page.route('https://invidious.test/api/v1/channels/**', route => route.fulfill({
    json: { error: 'This channel is unavailable' }
  }))

  await openChannelTab(page, CACHED_CHANNEL_ID)

  const cachedChannel = page.locator('.channelDetails:visible')
  await expect(cachedChannel.locator('.name')).toHaveText('Deleted Channel')
  await expect(cachedChannel.locator('img.thumbnail')).toHaveCount(0)
  const fallbackAvatar = cachedChannel.locator('.thumbnail:not(img)')
  await expect(fallbackAvatar).toBeVisible()
  await expect(fallbackAvatar).toHaveCSS('font-size', '100px')

  const cachedChannelTab = page.locator(sel.activeTab)
  await expect(cachedChannelTab.locator('.tabAvatar')).toHaveCount(0)
  await expect(cachedChannelTab.locator('.tabPageIcon'))
    .toHaveAttribute('data-icon', 'circle-user')

  await page.evaluate(() => window.ftElectron.tabs.setPreviewCapturePaused(true))
  try {
    await cachedChannel.hover()
    await cachedChannelTab.hover()
    const tooltipPreview = page.locator('.tabTooltipPreview')
    await expect(tooltipPreview).toBeVisible()
    await expect(tooltipPreview.locator('.tabTooltipPreviewAvatar')).toHaveCount(0)
    await expect(tooltipPreview.locator('.tabTooltipFallbackIcon'))
      .toHaveAttribute('data-icon', 'circle-user')

    await page.keyboard.down('Control')
    try {
      await page.keyboard.press('Tab')
      const switcherItem = page.locator('.tabSwitcherItem', { hasText: 'Deleted Channel' })
      await expect(switcherItem).toBeVisible()
      const switcherTitleAvatar = switcherItem.locator('.tabSwitcherTitleAvatar')
      const switcherTitleIcon = switcherItem.locator('.tabSwitcherTitleIcon')
      await expect(switcherTitleAvatar.or(switcherTitleIcon)).toHaveCount(1)
      if (await switcherTitleAvatar.count() > 0) {
        await switcherTitleAvatar.dispatchEvent('error')
      }
      await expect(switcherItem.locator('.tabSwitcherTitleIcon'))
        .toHaveAttribute('data-icon', 'circle-user')
    } finally {
      await page.keyboard.up('Control')
    }
  } finally {
    await page.evaluate(() => window.ftElectron.tabs.setPreviewCapturePaused(false))
  }

  await openChannelTab(page, UNKNOWN_CHANNEL_ID)

  const unknownChannel = page.locator('.channelDetails:visible')
  await expect(unknownChannel.locator('.name')).toHaveText('Channel name unavailable')
  await expect(page.locator(sel.activeTab)).toContainText('Channel name unavailable')

  await page.evaluate(() => {
    const app = document.querySelector('#app').__vue_app__
    const i18n = app._context.provides[app.__VUE_I18N_SYMBOL__].global
    i18n.setLocaleMessage('e2e', {
      Channel: { 'Channel Name Unavailable': 'Localized unavailable name' }
    })
    i18n.locale.value = 'e2e'
  })

  await expect(unknownChannel.locator('.name')).toHaveText('Localized unavailable name')
  await expect(page.locator(sel.activeTab)).toContainText('Localized unavailable name')
})
