import { test, expect, goTo, sel, waitForAppReady } from '../../helpers/app.mjs'

const shortcutModifier = process.platform === 'darwin' ? 'Meta' : 'Control'

async function historyLinkLabel(page) {
  await goTo(page, 'subscriptions')
  return page.locator(`${sel.sideNavLink('history')}:visible`).first().locator('.navLabel')
}

test.describe('YouTube links', () => {
  test.use({
    seed: {
      settings: { externalLinkHandling: 'openLinkAfterPrompt' }
    }
  })

  test('opens mobile video links in the app', async ({ page }) => {
    const link = page.locator('body').getByRole('link', { name: 'Mobile YouTube video' })
    await page.locator('body').evaluate((body) => {
      body.insertAdjacentHTML(
        'beforeend',
        '<a href="https://m.youtube.com/watch?v=jNQXAC9IVRw">Mobile YouTube video</a>'
      )
    })

    await link.click()

    await expect(page.getByText('Are you sure you want to open this link?')).not.toBeVisible()
    await expect(page).toHaveURL(/#\/watch\/jNQXAC9IVRw/)
  })
})

test('middle-clicking an internal link opens it in a background tab', async ({ page }) => {
  const linkLabel = await historyLinkLabel(page)

  await linkLabel.click({ button: 'middle' })

  await expect(page.locator(sel.tabs)).toHaveCount(2)
  await expect(page.locator(sel.tabs).first()).toHaveClass(/active/)
  await expect(page).toHaveURL(/#\/subscriptions$/)
  await expect.poll(() => page.evaluate(async () => {
    const state = await window.ftElectron.tabs.getState()
    return state.tabs.find(tab => tab.id !== state.activeTabId)?.route.fullPath
  })).toBe('/history')
})

test('Ctrl or Cmd-clicking an internal link opens it in an active tab', async ({ page }) => {
  const linkLabel = await historyLinkLabel(page)

  await linkLabel.click({ modifiers: [shortcutModifier] })

  await expect(page.locator(sel.tabs)).toHaveCount(2)
  await expect(page.locator(sel.tabs).nth(1)).toHaveClass(/active/)
  await expect(page).toHaveURL(/#\/history$/)
})

test('shift-middle-clicking an internal link opens it in a new window', async ({ app, page }) => {
  const linkLabel = await historyLinkLabel(page)

  const [newWindow] = await Promise.all([
    app.electronApp.waitForEvent('window', { timeout: 5000 }),
    linkLabel.click({ button: 'middle', modifiers: ['Shift'] })
  ])
  await waitForAppReady(newWindow)

  await expect(newWindow).toHaveURL(/#\/history$/)
  await expect(page.locator(sel.tabs)).toHaveCount(1)
  await expect(page).toHaveURL(/#\/subscriptions$/)
})

test.describe('channel About links', () => {
  const instanceUrl = 'https://invidious.test'
  const channelId = 'UCaaaaaaaaaaaaaaaaaaaaaa'
  const featuredChannelId = 'UCbbbbbbbbbbbbbbbbbbbbbb'

  test.use({
    seed: {
      settings: {
        backendPreference: 'invidious',
        defaultInvidiousInstance: instanceUrl
      }
    }
  })

  test('middle-clicking a featured channel keeps the channel tab active', async ({ page }) => {
    await page.route(`${instanceUrl}/api/v1/channels/**`, route => route.fulfill({
      json: {
        author: 'Source channel',
        authorId: channelId,
        authorBanners: [],
        authorThumbnails: [],
        subCount: 1,
        totalViews: 2,
        joined: 1_700_000_000,
        autoGenerated: false,
        isFamilyFriendly: true,
        description: '',
        descriptionHtml: '',
        allowedRegions: [],
        tabs: [],
        latestVideos: [],
        relatedChannels: [{
          author: 'Featured channel',
          authorId: featuredChannelId,
          authorThumbnails: []
        }]
      }
    }))

    const sourceTab = await page.evaluate(id => window.ftElectron.tabs.create({
      route: `/channel/${id}`,
      makeActive: true
    }), channelId)

    await page.getByRole('tab', { name: 'About' }).click()
    await page.getByRole('link', { name: 'Featured channel' }).click({ button: 'middle' })

    await expect(page.locator(sel.tabs)).toHaveCount(3)
    await expect(page.locator(`.tab[data-tab-id="${sourceTab.id}"]`)).toHaveClass(/active/)
    await expect(page).toHaveURL(new RegExp(`#/channel/${channelId}/about$`))
  })
})
