import { test, expect, sel } from '../../helpers/app.mjs'

const INSTANCE_URL = 'https://invidious.test'
const CHANNEL_ID = 'UCaaaaaaaaaaaaaaaaaaaaaa'
const PLAYLIST_ID = 'PLaaaaaaaaaaaaaaaaaaaaaa'
const AUTHOR_THUMBNAIL = 'https://yt3.ggpht.com/channel-avatar=s176-c-k-c0x00ffffff-no-rj'
const PROXIED_AUTHOR_THUMBNAIL = `${INSTANCE_URL}/ggpht/channel-avatar=s176-c-k-c0x00ffffff-no-rj`

function channelResponse() {
  return {
    author: 'Small thumbnail channel',
    authorId: CHANNEL_ID,
    authorBanners: [],
    authorThumbnails: [{ url: AUTHOR_THUMBNAIL, width: 176, height: 176 }],
    subCount: 1,
    totalViews: 2,
    joined: 1_700_000_000,
    autoGenerated: false,
    isFamilyFriendly: true,
    description: '',
    descriptionHtml: '',
    allowedRegions: [],
    tabs: [],
    latestVideos: [],
    relatedChannels: []
  }
}

async function openChannel(page) {
  const tab = await page.evaluate((channelId) => window.ftElectron.tabs.create({
    route: `/channel/${channelId}`,
    makeActive: false
  }), CHANNEL_ID)
  await page.locator(`.tab[data-tab-id="${tab.id}"]`).click()
}

test.use({
  seed: {
    settings: {
      backendPreference: 'invidious',
      defaultInvidiousInstance: INSTANCE_URL
    }
  }
})

test.beforeEach(async ({ page }) => {
  await page.route(PROXIED_AUTHOR_THUMBNAIL, route => route.fulfill({
    contentType: 'image/svg+xml',
    body: '<svg xmlns="http://www.w3.org/2000/svg"/>'
  }))
})

test('loads a playlist with one author thumbnail', async ({ page }) => {
  await page.route(`${INSTANCE_URL}/api/v1/playlists/**`, route => route.fulfill({
    json: {
      title: 'Small thumbnail playlist',
      playlistId: PLAYLIST_ID,
      author: 'Test channel',
      authorId: CHANNEL_ID,
      authorThumbnails: [{ url: AUTHOR_THUMBNAIL, width: 176, height: 176 }],
      description: '',
      descriptionHtml: '',
      videoCount: 0,
      viewCount: 0,
      updated: 1_756_000_000,
      videos: []
    }
  }))

  await page.locator(sel.searchInput).fill(`https://www.youtube.com/playlist?list=${PLAYLIST_ID}`)
  await page.locator(sel.searchInput).press('Enter')

  await expect(page).toHaveURL(new RegExp(`#/playlist/${PLAYLIST_ID}`))
  await expect(page.locator('.playlistTitle')).toHaveText('Small thumbnail playlist')
  await expect(page.locator('.playlistChannel .channelThumbnail'))
    .toHaveAttribute('src', PROXIED_AUTHOR_THUMBNAIL)
})

test('loads a channel with one author thumbnail', async ({ page }) => {
  await page.route(`${INSTANCE_URL}/api/v1/channels/**`, route => route.fulfill({
    json: channelResponse()
  }))

  await openChannel(page)

  const channel = page.locator('.channelDetails:visible')
  await expect(channel.locator('.name')).toHaveText('Small thumbnail channel')
  await expect(channel.locator('img.thumbnail')).toHaveAttribute('src', PROXIED_AUTHOR_THUMBNAIL)
  await expect(page.locator('.toast', { hasText: 'Invidious API Error' })).toHaveCount(0)
})

test('configures subscription options before subscribing', async ({ page }) => {
  await page.route(`${INSTANCE_URL}/api/v1/channels/**`, route => route.fulfill({
    json: channelResponse()
  }))
  await openChannel(page)

  const channel = page.locator('.channelDetails:visible')
  await channel.getByRole('button', { name: 'Subscription settings' }).click()
  const dropdown = page.locator('body > .profileDropdown')
  const shorts = dropdown.getByRole('checkbox', { name: 'Shorts' })
  await expect(shorts).toHaveAttribute('aria-checked', 'true')
  await shorts.click()

  const dailyLimit = dropdown.getByRole('combobox', { name: 'Videos per day' })
  await dailyLimit.click()
  await page.getByRole('option', { name: '2', exact: true }).click()
  await channel.getByRole('button', { name: 'Subscribe', exact: true }).click()

  await expect(channel.getByRole('button', { name: 'Unsubscribe', exact: true })).toBeVisible()
  await expect.poll(() => page.evaluate(channelId => {
    const subscriptions = document.querySelector('#app').__vue_app__.config.globalProperties
      .$store.getters.getActiveProfile.subscriptions
    const subscription = subscriptions.find(item => item.id === channelId)
    return subscription && {
      dailyVideoLimit: subscription.dailyVideoLimit,
      feedTypes: subscription.feedTypes,
      showMembersOnly: subscription.showMembersOnly
    }
  }, CHANNEL_ID)).toEqual({
    dailyVideoLimit: 2,
    feedTypes: ['videos', 'live', 'posts'],
    showMembersOnly: false
  })
})
