version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "PR: waiting for review"
      - "PR: dependencies"
    open-pull-requests-limit: 15
    allow:
      - dependency-name: "@hpke/core"
      - dependency-name: "@iconify-json/material-symbols"
      - dependency-name: "@iconify-json/ri"
      - dependency-name: "@iconify-json/simple-icons"
      - dependency-name: "@iconify/utils"
      - dependency-name: "@iconify/vue"
      - dependency-name: "@playwright/test"
      - dependency-name: "@vot.js/core"
      - dependency-name: "eld"
      - dependency-name: "font-list"
      - dependency-name: "overlayscrollbars"
      - dependency-name: "qr-scanner"
      - dependency-name: "qrcode"
      - dependency-name: "vue-sonner"
      - dependency-name: "yaml"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "PR: waiting for review"
      - "PR: dependencies"
    groups:
      "actions/cache":
        patterns:
          - "actions/cache/*"
      "github/codeql-action":
        patterns:
          - "github/codeql-action/*"
