version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "PR: waiting for review"
      - "PR: dependencies"
    open-pull-requests-limit: 15
    allow:
      - dependency-name: "@capacitor-community/keep-awake"
      - dependency-name: "@capacitor-community/screen-brightness"
      - dependency-name: "@capacitor/android"
      - dependency-name: "@capacitor/app"
      - dependency-name: "@capacitor/barcode-scanner"
      - dependency-name: "@capacitor/browser"
      - dependency-name: "@capacitor/cli"
      - dependency-name: "@capacitor/core"
      - dependency-name: "@capacitor/device"
      - dependency-name: "@capacitor/filesystem"
      - dependency-name: "@capacitor/local-notifications"
      - dependency-name: "@capacitor/share"
      - dependency-name: "@capawesome/capacitor-app-shortcuts"
      - dependency-name: "@capawesome/capacitor-clipboard"
      - dependency-name: "@capawesome/capacitor-screen-orientation"
      - dependency-name: "@capawesome/capacitor-settings-launcher"
      - dependency-name: "@capawesome/capacitor-volume"
      - dependency-name: "@fontsource-variable/geist"
      - dependency-name: "@hpke/core"
      - dependency-name: "@iconify-json/material-symbols"
      - dependency-name: "@iconify-json/ri"
      - dependency-name: "@iconify-json/simple-icons"
      - dependency-name: "@iconify/utils"
      - dependency-name: "@iconify/vue"
      - dependency-name: "@jitl/quickjs-wasmfile-release-sync"
      - dependency-name: "@lezer/html"
      - dependency-name: "@lezer/markdown"
      - dependency-name: "@playwright/test"
      - dependency-name: "@vot.js/core"
      - dependency-name: "dbus-native"
      - dependency-name: "eld"
      - dependency-name: "entities"
      - dependency-name: "font-list"
      - dependency-name: "node-gyp"
      - dependency-name: "overlayscrollbars"
      - dependency-name: "qr-scanner"
      - dependency-name: "qrcode"
      - dependency-name: "quickjs-emscripten-core"
      - dependency-name: "vue-sonner"
      - dependency-name: "yaml"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "PR: waiting for review"
      - "PR: dependencies"
    groups:
      "actions/cache":
        patterns:
          - "actions/cache/*"
      "github/codeql-action":
        patterns:
          - "github/codeql-action/*"
