'PR: waiting for review':
- changed-files:
  - any-glob-to-any-file: '**'

translations:
- head-branch: ['^weblate-translations$']

'PR: dependencies':
- any:
  - changed-files:
    - any-glob-to-any-file: ['pnpm-lock.yaml', 'package.json']
