# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

reviews:
  high_level_summary: false
  request_changes_workflow: true
  auto_review:
    ignore_title_keywords:
      - "Translations update from Weblate"
    labels:
      - "!translations"
  auto_review:
    enabled: false
    auto_incremental_review: false
