# https://github.com/pnpm/pnpm/issues/11070
# Disable until GitHub dependabot got pnpm >= 10.33.0 installed
# dedupePeers: true

# https://pnpm.io/next/settings#allowbuilds
allowBuilds:
  '@parcel/watcher': true
  electron: true
  electron-winstaller: false # We build NSIS installers on Windows, not squirrel ones
  lefthook: true # Installing git hooks
  unrs-resolver: false # Works around an npm specific optional dependencies bug, so we don't need it with pnpm

overrides:
  uuid@<11.1.1: '>=11.1.1'
  yauzl: '>=3.3.1'

minimumReleaseAgeExclude:
  - "youtubei.js"

patchedDependencies:
  shaka-player@5.1.12: patches/shaka-player@5.1.12.patch
  vue-sonner@2.0.9: patches/vue-sonner@2.0.9.patch
  youtubei.js@17.2.0: patches/youtubei.js@17.2.0.patch
