blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/OpenTubeX/OpenTubeX/discussions/categories/general
    about: View discussions or start one yourself
  - name: Questions
    url: https://github.com/OpenTubeX/OpenTubeX/discussions/categories/q-a
    about: Ask and answer questions
  - name: Translate FreeTube
    url: https://hosted.weblate.org/engage/free-tube/
    about: Help translate FreeTube on Weblate
  - name: OpenTubeX Documentation
    url: https://opentubex.org/
    about: View the Documentation to find all relevant information about OpenTubeX
