import assert from 'node:assert/strict'
import test from 'node:test'

import {
  assess,
  backfillCandidates,
  formatReply,
  hasBotReaction,
  shouldReply,
  validateDecision
} from '../../_scripts/issueTriage.mjs'
import { eligibleAuthor } from '../../_scripts/issueTriageCommon.mjs'

test('triage excludes D3SOX and bot issue authors', () => {
  assert.equal(eligibleAuthor({ login: 'D3SOX', __typename: 'User' }), false)
  assert.equal(eligibleAuthor({ login: 'd3sox', __typename: 'User' }), false)
  assert.equal(eligibleAuthor({ login: 'app', __typename: 'Bot' }), false)
  assert.equal(eligibleAuthor({ login: 'app[bot]', __typename: 'User' }), false)
  assert.equal(eligibleAuthor({ login: 'reporter', __typename: 'User' }), true)
  assert.equal(eligibleAuthor(null), false)
})

test('model decisions cannot publish arbitrary labels or replies', () => {
  assert.deepEqual(validateDecision({ labels: ['bug'], reply: 'none', source: 'none' }), {
    labels: ['bug'], reply: 'none', source: 'none'
  })
  assert.throws(() => validateDecision({ labels: ['wontfix'], reply: 'none', source: 'none' }))
  assert.throws(() => validateDecision({ labels: ['bug', 'bug'], reply: 'none', source: 'none' }))
  assert.throws(() => validateDecision({ labels: [], reply: 'Close this issue', source: 'none' }))
  assert.throws(() => validateDecision({ labels: [], reply: 'answer', source: 'none' }))
  assert.throws(() => validateDecision({ labels: [], reply: 'none', source: 'extra-features' }))
})

test('triage avoids repeated or intrusive replies', () => {
  const reply = 'Which OpenTubeX version are you using?'
  const formatted = formatReply(reply)
  assert.equal(formatted, '> [!NOTE]  \n> 🤖 This reply was generated by AI and may be inaccurate.\n\nWhich OpenTubeX version are you using?')
  assert.equal(shouldReply([], reply), true)
  assert.equal(shouldReply([{ body: reply, author: { login: 'other' } }], reply), false)
  assert.equal(shouldReply([{ body: formatted, author: { login: 'github-actions[bot]' } }], reply), false)
  assert.equal(shouldReply([{ body: `> [!NOTE]  \n> 🤖 This question was generated by AI and may be inaccurate.\n\n${reply}` }], reply), false)
  assert.equal(shouldReply([{
    body: 'Looking into it',
    authorAssociation: 'COLLABORATOR',
    author: { login: 'maintainer' }
  }], reply), false)
  assert.equal(shouldReply([{
    body: 'Automated response',
    author: { login: 'actions[bot]', __typename: 'Bot' }
  }], reply), false)
})

test('manual backfill excludes pull requests, D3SOX, and bots', () => {
  const issues = [
    { number: 1, user: { login: 'reporter', type: 'User' } },
    { number: 2, user: { login: 'reporter', type: 'User' }, pull_request: {} },
    { number: 3, user: { login: 'D3SOX', type: 'User' } },
    { number: 4, user: { login: 'dependabot[bot]', type: 'Bot' } }
  ]
  assert.deepEqual(backfillCandidates(issues).map(issue => issue.number), [1])
})

test('only the Actions bot eyes reaction marks an issue as triaged', () => {
  assert.equal(hasBotReaction([{ content: 'eyes', user: { login: 'reporter' } }]), false)
  assert.equal(hasBotReaction([{ content: '+1', user: { login: 'github-actions[bot]' } }]), false)
  assert.equal(hasBotReaction([{ content: 'eyes', user: { login: 'github-actions[bot]' } }]), true)
})

test('triage uses the final structured output when the response has multiple messages', async t => {
  const originalFetch = globalThis.fetch
  t.after(() => { globalThis.fetch = originalFetch })
  globalThis.fetch = async () => ({
    ok: true,
    json: async () => ({
      status: 'completed',
      output: [
        { content: [{ type: 'output_text', text: '{"labels":["bug"],"reply":"none","source":"none"}' }] },
        { content: [{ type: 'output_text', text: '{"labels":["question"],"reply":"version","source":"none"}' }] }
      ]
    })
  })
  const issue = { title: 'Report', body: '', comments: { nodes: [] } }
  assert.deepEqual(await assess(issue), { labels: ['question'], reply: 'version', source: 'none' })
})

test('triage retries a response that exhausted its output tokens', async t => {
  const originalFetch = globalThis.fetch
  t.after(() => { globalThis.fetch = originalFetch })
  const budgets = []
  const efforts = []
  globalThis.fetch = async (_, options) => {
    const request = JSON.parse(options.body)
    budgets.push(request.max_output_tokens)
    efforts.push(request.reasoning.effort)
    return {
      ok: true,
      json: async () => budgets.length === 1
        ? { status: 'incomplete', incomplete_details: { reason: 'max_output_tokens' } }
        : {
            status: 'completed',
            output: [{ content: [{ type: 'output_text', text: '{"labels":["bug"],"reply":"none","source":"none"}' }] }]
          }
    }
  }
  const issue = { title: 'Report', body: '', comments: { nodes: [] } }
  assert.deepEqual(await assess(issue), { labels: ['bug'], reply: 'none', source: 'none' })
  assert.deepEqual(budgets, [250, 1000])
  assert.deepEqual(efforts, ['low', 'low'])
})

test('triage answers an existing-feature request from verified documentation', async t => {
  const originalFetch = globalThis.fetch
  t.after(() => { globalThis.fetch = originalFetch })
  const requests = []
  globalThis.fetch = async (_, options) => {
    const request = JSON.parse(options.body)
    requests.push(request)
    const output = requests.length === 1
      ? { labels: ['enhancement'], reply: 'answer', source: 'extra-features' }
      : {
          answer: 'Open the video menu and choose Add to Queue. Manage the queue in the watch page side panel.',
          evidence: 'Queue videos from their three-dot menus, then manage and drag to reorder them in a side panel on the watch page.'
        }
    return { ok: true, json: async () => ({
      status: 'completed',
      output: [{ content: [{ type: 'output_text', text: JSON.stringify(output) }] }]
    }) }
  }
  const issue = {
    title: 'Queue Feature for videos and shorts',
    body: 'Having the ability to create a queue of videos to watch would be very useful.',
    comments: { nodes: [] }
  }
  const result = await assess(issue, {
    readSource: async () => '### Watch queue\n\nQueue videos from their three-dot menus, then manage and drag to reorder them in a side panel on the watch page.'
  })
  assert.equal(requests.length, 2)
  assert.equal(Object.hasOwn(requests[1], 'signal'), false)
  assert.equal(result.reply, 'answer')
  assert.deepEqual(result.labels, ['enhancement'])
  assert.match(result.answer, /Add to Queue/)
  assert.match(result.answer, /https:\/\/opentubex\.org\/extra-features\/#watch-queue/)
})

test('feature templates check existing support even when the first decision requests silence', async t => {
  const originalFetch = globalThis.fetch
  t.after(() => { globalThis.fetch = originalFetch })
  let calls = 0
  globalThis.fetch = async () => {
    calls++
    const output = calls === 1
      ? { labels: ['enhancement'], reply: 'none', source: 'none' }
      : {
          answer: 'Open the video menu and choose Add to Queue.',
          evidence: 'Queue videos from their three-dot menus, then manage and drag to reorder them in a side panel on the watch page.'
        }
    return { ok: true, json: async () => ({
      status: 'completed',
      output: [{ content: [{ type: 'output_text', text: JSON.stringify(output) }] }]
    }) }
  }
  const issue = {
    title: 'Queue Feature for videos and shorts',
    body: '### Issue Labels\n\nnew feature\n\n### Proposed Solution\n\nCreate a queue.',
    comments: { nodes: [] }
  }
  const result = await assess(issue, {
    readSource: async () => '### Watch queue\n\nQueue videos from their three-dot menus, then manage and drag to reorder them in a side panel on the watch page.'
  })
  assert.equal(calls, 2)
  assert.equal(result.reply, 'answer')
  assert.deepEqual(result.labels, ['enhancement'])
})

test('triage stays silent when a proposed answer lacks source evidence', async t => {
  const originalFetch = globalThis.fetch
  t.after(() => { globalThis.fetch = originalFetch })
  let calls = 0
  globalThis.fetch = async () => {
    calls++
    const output = calls === 1
      ? { labels: ['enhancement'], reply: 'answer', source: 'extra-features' }
      : { answer: 'OpenTubeX has a queue.', evidence: 'This claim is absent from the guide.' }
    return { ok: true, json: async () => ({
      status: 'completed',
      output: [{ content: [{ type: 'output_text', text: JSON.stringify(output) }] }]
    }) }
  }
  const issue = { title: 'Queue', body: '', comments: { nodes: [] } }
  const result = await assess(issue, { readSource: async () => '### Watch queue\nQueue videos from the menu.' })
  assert.equal(calls, 2)
  assert.equal(result.answer, null)
  assert.deepEqual(result.labels, ['enhancement'])
})
