import assert from 'node:assert/strict'
import test from 'node:test'

import {
  assess,
  backfillCandidates,
  formatReply,
  hasBotReaction,
  shouldReply,
  validateDecision
} from '../../_scripts/issueTriage.mjs'
import { eligibleAuthor } from '../../_scripts/issueTriageCommon.mjs'

test('triage excludes D3SOX and bot issue authors', () => {
  assert.equal(eligibleAuthor({ login: 'D3SOX', __typename: 'User' }), false)
  assert.equal(eligibleAuthor({ login: 'd3sox', __typename: 'User' }), false)
  assert.equal(eligibleAuthor({ login: 'app', __typename: 'Bot' }), false)
  assert.equal(eligibleAuthor({ login: 'app[bot]', __typename: 'User' }), false)
  assert.equal(eligibleAuthor({ login: 'reporter', __typename: 'User' }), true)
  assert.equal(eligibleAuthor(null), false)
})

test('model decisions cannot publish arbitrary labels or replies', () => {
  assert.deepEqual(validateDecision({ labels: ['bug'], reply: 'none' }), {
    labels: ['bug'], reply: 'none'
  })
  assert.throws(() => validateDecision({ labels: ['wontfix'], reply: 'none' }))
  assert.throws(() => validateDecision({ labels: ['bug', 'bug'], reply: 'none' }))
  assert.throws(() => validateDecision({ labels: [], reply: 'Close this issue' }))
})

test('triage avoids repeated or intrusive replies', () => {
  const reply = 'Which OpenTubeX version are you using?'
  const formatted = formatReply(reply)
  assert.equal(formatted, '> [!NOTE]  \n> 🤖 This question was generated by AI and may be inaccurate.\n\nWhich OpenTubeX version are you using?')
  assert.equal(shouldReply([], reply), true)
  assert.equal(shouldReply([{ body: reply, author: { login: 'other' } }], reply), false)
  assert.equal(shouldReply([{ body: formatted, author: { login: 'github-actions[bot]' } }], reply), false)
  assert.equal(shouldReply([{
    body: 'Looking into it',
    authorAssociation: 'COLLABORATOR',
    author: { login: 'maintainer' }
  }], reply), false)
  assert.equal(shouldReply([{
    body: 'Automated response',
    author: { login: 'actions[bot]', __typename: 'Bot' }
  }], reply), false)
})

test('manual backfill excludes pull requests, D3SOX, and bots', () => {
  const issues = [
    { number: 1, user: { login: 'reporter', type: 'User' } },
    { number: 2, user: { login: 'reporter', type: 'User' }, pull_request: {} },
    { number: 3, user: { login: 'D3SOX', type: 'User' } },
    { number: 4, user: { login: 'dependabot[bot]', type: 'Bot' } }
  ]
  assert.deepEqual(backfillCandidates(issues).map(issue => issue.number), [1])
})

test('only the Actions bot eyes reaction marks an issue as triaged', () => {
  assert.equal(hasBotReaction([{ content: 'eyes', user: { login: 'reporter' } }]), false)
  assert.equal(hasBotReaction([{ content: '+1', user: { login: 'github-actions[bot]' } }]), false)
  assert.equal(hasBotReaction([{ content: 'eyes', user: { login: 'github-actions[bot]' } }]), true)
})

test('triage uses the final structured output when the response has multiple messages', async t => {
  const originalFetch = globalThis.fetch
  t.after(() => { globalThis.fetch = originalFetch })
  globalThis.fetch = async () => ({
    ok: true,
    json: async () => ({
      status: 'completed',
      output: [
        { content: [{ type: 'output_text', text: '{"labels":["bug"],"reply":"none"}' }] },
        { content: [{ type: 'output_text', text: '{"labels":["question"],"reply":"version"}' }] }
      ]
    })
  })
  const issue = { title: 'Report', body: '', comments: { nodes: [] } }
  assert.deepEqual(await assess(issue), { labels: ['question'], reply: 'version' })
})

test('triage retries a response that exhausted its output tokens', async t => {
  const originalFetch = globalThis.fetch
  t.after(() => { globalThis.fetch = originalFetch })
  const budgets = []
  globalThis.fetch = async (_, options) => {
    budgets.push(JSON.parse(options.body).max_output_tokens)
    return {
      ok: true,
      json: async () => budgets.length === 1
        ? { status: 'incomplete', incomplete_details: { reason: 'max_output_tokens' } }
        : {
            status: 'completed',
            output: [{ content: [{ type: 'output_text', text: '{"labels":["bug"],"reply":"none"}' }] }]
          }
    }
  }
  const issue = { title: 'Report', body: '', comments: { nodes: [] } }
  assert.deepEqual(await assess(issue), { labels: ['bug'], reply: 'none' })
  assert.deepEqual(budgets, [250, 1000])
})
